### ISSUE TITLE
Question: Incremental Builds

### ISSUE THREAD

**Issue by kentcdodds** [joliss/broccoli-uglify-js#6]
I have a huge application at work and we're trying to speed up our grunt build. One of the bottlenecks is our uglify task. Part of the reason is we're minifying vendor files like jQuery, Angular, lodash, d3, etc every time we run the build.

My question is, I don't see [broccoli-caching-writer](https://github.com/rjackson/broccoli-caching-writer) as a dependency so I'm wondering if using this plugin would give us incremental builds. Thanks!

**Comment by joliss** [comment]
The Filter baseclass already provides caching. So files should only be re-uglified if they have changed.

However, if you're running broccoli-uglify-js on a big concatenated file that includes vendor files, it will always be slow. I don't think there's anything we can do about this - basically the best advice in this case is to only uglify in production.
